MEME_SORT_FOLDER=/home/sirfozzie/Documents/Zemez/Zemes_SORT
MEME_TARGET_FOLDER=/home/sirfozzie/Documents/Zemez
MEME_LOG_FILE_PATH=/home/sirfozzie/Documents/Zemez/MemeFilerRenameScript.ps1
MEMEFILER_LAUNCH_PAGE=http://localhost:9003

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%p] %c %M - %msg%n
logging.level.root=INFO
logging.level.com.codef=INFO

spring.jpa.open-in-view=false

server.port=9003